const RESPONSES = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOCONTENT: 204,
  BADREQUEST: 400,
  UN_AUTHORIZED: 401,
  INVALID_REQ: 422,
  FORBIDDEN: 403,
  NOTFOUND: 404,
  TIMEOUT: 408,
  TOOMANYREQ: 429,
  INTERNALSERVER: 500,
  BADGATEWAYS: 502,
  SERVICEUNAVILABLE: 503,
  GATEWAYTIMEOUT: 504,
};

const RES_MSG = {
  NO_DATA: "No Data Found.",
  PASSWORD_MISMATCHED: "Password Missmatched.",
  VALIDATION_FAILED_FROM_SMART_CONTRACT:
    "Validation Failed From Smart Contract",
  SAME_PASSWORD: "New Password Can Not Be Same As Old Password.",
  CHECK_CREDENTIALS: "Check Your Email And Password.",
  USER_NOT_FOUND: "User Not Found.Please Register Yourself First.",
  WRONG_PASSWORD: "Invalid Credentials.",
  LOGIN_LATER: "Login After The Cooldown Time.",
  GREY_LISTED: "Too Many Invalid Attempts.User Locked For 2 Hours.",
  BADREQUEST: "Bad Request.",
  INTERNAL_SERVER_ERROR: "Internal Server Error.",
  PROFILE_PIC_ERROR: "Check The Profile Picture Format(PNG|JPG|JPEG).",
  SUCCESS: "Success.",
  REGISTER_SUCCESS: "Registered Successfully.",
  LOGIN_SUCCESS: "Logged In Successfully.",
  LOGOUT_SUCCESS: "Logged Out Successfully.",
  REGISTER_DUPLICACY: "Email Already Used.",
  INVALID_OLD_PASSWORD: "Invalid Old Password.",
  AUDITOR_NOT_FOUND: "Auditor Email Not Registered.",
  BID_SUCCESS: "Bid Request Submitted Successfully.",
  BID_ACCEPTED: "Bid Request Accepted Successfully.",
  BID_NOT_POSSIBLE: "Bid Is No Longer Avaiable For This Post.",
  POSTER_NOT_FOUND: "Audit Poster Email missmatched.",
  UN_AUTHORIZED: "Invalid/Unauthorised Access.",
  TFA_SUCCESS: "2FA Enabled.",
  TFA_DISABLED: "2FA Disabled.",
  TFA_FAIL: "Invalid OTP.",
  TFA_STATUS: "2FA Status Fetched Successfully.",
  POST_ID_MISMATCHED: "Post ID Mismatched With Given Email Address.",
  IDENTICAL_REQUEST: "Poster Email Must Be Different From Bidder Email.",
  POST_REGISTERED: "Audit Post Created.",
  PRE_REGISTERED: "Audit Pre Registered.",
  PASSWORD_UPDATED:
    "Password Changed Successfully.Please Log In Again With New Password.",
  DATE_TRESPASSED: "Estimated Date Not Eligible.",
  PROFILE_UPDATED: "Profile Updated Successfully.",
  REPORT_SUBMITTED: "Reported Submitted Successfully.",
  EVENT_RETRIVED: "Event Fetched Sucessfully.",
  EVENT_NULL: "No Events Found.",
  ALREADY_VOTED: "Already Voted.",
  VOTE_TIME_CROSSED: "Cannot Proceed To Vote After Deadline",
  NOT_ARBITER: "Not Arbiter Or Wallet Address Not Updated.",
  SAME_BID: "Cannot Place Same Bid Twice.",
  SUBMIT_MISMATCHED: "Submit Count Is Not Matching The Audit Types.",
  AUDIT_SUBMITTED: "Audit Report Submitted Successfully.",
  SUBMIT_DECLINED: "Submit Is Declined.Post Under Arbiteration.",
  EXTENTION_REQUEST_SENT: "Extension Request Sent Successfully",
  PATRON_REJECTED: "Patron rejected the request",
  EXTENSION_REQUEST_ALREADY_EXISTS: "Extension Request Already Exists",
};
module.exports = {
  RESPONSES,
  RES_MSG,
};
